version: '3'

services:
  web:
    image: openconceptlab/oclweb3:${TAG-latest}
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "4002:4002"
    restart: on-failure
    environment:
      - API_URL=${API_URL-http://127.0.0.1:8000}
      - NODE_ENV=${NODE_ENV-development}
      - WEB_PORT=4002
      - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY-6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI}
      - GA_ACCOUNT_ID=${GA_ACCOUNT_ID-UA-000000-01}
      - ANALYTICS_API
      - ERRBIT_URL
      - ERRBIT_KEY
      - HOTJAR_ID
